[package]
name    = "game2d"
version = "0.1.0"
authors = ["Victor Albertsson <victor.albertsson@live.se>"]
edition = "2018"

[dependencies]
winit       = "0.22.2"
shaderc     = "0.6.2"
vulkano     = "0.19.0"
vulkano-win = "0.19.0"
